/** Privileged operation categories that require an explicit decision. */
export type ApprovalOperation =
  | "read"
  | "write"
  | "edit"
  | "list"
  | "find"
  | "grep"
  | "skill"
  | "todo"
  | "session"
  | "shell"
  | "network";

/** Coarse risk label shown to the approving user. */
export type ApprovalRisk = "low" | "medium" | "high";

/** One per-operation authorization request. */
export interface ApprovalRequest {
  /** Stable id used by UI callbacks. Generated by the gate when omitted. */
  id?: string;
  /** Operation category. */
  operation: ApprovalOperation;
  /** Path, host, command, or other exact target for this operation. */
  target: string;
  /** Short operation summary that avoids file contents and secrets. */
  summary?: string;
  /** Coarse risk label. */
  risk: ApprovalRisk;
  /** Session id associated with the request. */
  sessionId: string;
  /** Turn id associated with the request. */
  turnId: string;
  /** Deny automatically after this many milliseconds. */
  timeoutMs: number;
}

/** Decision returned by an approval gate. */
export interface ApprovalDecision {
  /** True only when the configured approver accepted the exact request. */
  approved: boolean;
  /** Machine-readable reason, such as approved, denied, timeout, or cancelled. */
  reason: string;
  /** ISO timestamp when the decision was made. */
  decidedAt: string;
  /** Optional actor id for audit trails. */
  decidedBy?: string;
}

/** Central app-layer authorization boundary for privileged adapters. */
export interface ApprovalGate {
  /** Requests a decision before the caller performs the privileged operation. */
  requestApproval(request: ApprovalRequest, signal?: AbortSignal): Promise<ApprovalDecision>;
  /** Returns whether the gate is currently waiting for a decision. */
  isPending?(): boolean;
}

/** Default timeout for operation approval requests. */
export const DEFAULT_APPROVAL_TIMEOUT_MS = 60_000;

/** Error thrown when a privileged operation is not approved. */
export class ApprovalDeniedError extends Error {
  /** Request that was denied. */
  readonly request: ApprovalRequest;
  /** Denial decision returned by the gate. */
  readonly decision: ApprovalDecision;

  /** Creates an error for a denied approval request. */
  constructor(request: ApprovalRequest, decision: ApprovalDecision) {
    super(`Approval denied for ${request.operation} ${request.target}: ${decision.reason}`);
    this.name = "ApprovalDeniedError";
    this.request = request;
    this.decision = decision;
  }
}

function decision(approved: boolean, reason: string, decidedBy?: string): ApprovalDecision {
  const result: ApprovalDecision = {
    approved,
    reason,
    decidedAt: new Date().toISOString(),
  };
  if (decidedBy !== undefined) result.decidedBy = decidedBy;
  return result;
}

/** Gate used by tests and explicitly trusted non-production harnesses. */
export function createAutoApprovalGate(decidedBy = "auto"): ApprovalGate {
  return {
    requestApproval: () => Promise.resolve(decision(true, "approved", decidedBy)),
    isPending: () => false,
  };
}

/** Gate used when no UI approval path is available. */
export function createDenyApprovalGate(reason = "approval_unavailable"): ApprovalGate {
  return {
    requestApproval: () => Promise.resolve(decision(false, reason)),
    isPending: () => false,
  };
}

/** Requests approval and throws if the operation is not approved. */
export async function requireApproval(
  gate: ApprovalGate,
  request: ApprovalRequest,
  signal?: AbortSignal,
): Promise<ApprovalDecision> {
  const decision = await gate.requestApproval(request, signal);
  if (!decision.approved) throw new ApprovalDeniedError(request, decision);
  return decision;
}

/** Creates a denied decision for custom gates. */
export function denyDecision(reason: string, decidedBy?: string): ApprovalDecision {
  return decision(false, reason, decidedBy);
}

/** Creates an approved decision for custom gates. */
export function approveDecision(decidedBy?: string): ApprovalDecision {
  return decision(true, "approved", decidedBy);
}
